baseurl: ""
url: "https://hacknotts.com"

exclude:
    - ".gitignore"
    - "CNAME"
    - "LICENSE"
    - "README.md"
    - "Gemfile"
    - "Gemfile.lock"
    - "Procfile"
    - "Rakefile"
    - "static.json"
    - "app.json"
    - [vendor]

sass:
    sass_dir: "assets/scss"
    style: "compressed"